const paragraphs = [
    "whatever you are be a good one",
    "Greetings from the real universe.",
    "The sign said there was road work ahead so he decided to speed up.",
    "There was no telling what thoughts would come from the machine.",
    "Car safety systems have come a long way, but he was out to prove they could be outsmarted.",
    "Sixty - Four comes asking for bread.",
    "He appeared to be confusingly perplexed.",
    "Toddlers feeding raccoons surprised even the seasoned park ranger.",
    "The wake behind the boat told of the past while the open sea for told life in the unknown future.",
    "Tuesdays are free if you bring a gnome costume.",
    "Trash covered the landscape like sprinkles do a birthday cake.",
    "Derry discovered that traffic cones make excellent megaphones.",
    "She advised him to come back at once.",
    "Linsday opened up her third bottle of wine of the night.",
    "He had a hidden stash underneath the floorboards in the back room of the house.",
    "Erin accidentally created a new universe.",
    "Andy loved to sleep on a bed of nails.",
    "There are no heroes in a punk rock band.",
    "I'm worried by the fact that my daughter looks to the local carpet seller as a role model.",
    "Cats are good pets, for they are clean and are not noisy.",
    "Written warnings in instruction manuals are worthless since rabbits can't read.",
    "They're playing the piano while flying in the plane.",
    "He was surprised that his immense laziness was inspirational to others.",
    "Barking dogs and screaming toddlers have the unique ability to turn friendly neighbors into cranky enemies.",
    "She used her own hair dye in the soup to give it more flavor.",
    "I checked to make sure that he was still alive.",
    "They throw cabbage that turns your brain into emotional baggage.",
    "The waitress was not amused when he ordered green eggs and ham.",
    "A dead duck doesn't fly backward.",
    "I can't believe this is the eighth time I'm smashing open my piggy bank on the same day!",
    "Three years later, the coffin was still full of Jello.",
    "The teenage boy was accused of breaking his arm simply to get out of the test.",
    "When confronted with a rotary dial phone the teenager was perplexed.",
    "He walked into the basement with the horror movie from the night before playing in his head.",
    "He had reached the point where he was paranoid about being paranoid.",
    "As he dangled from the rope deep inside the crevasse It took him a month to finish the meal.",
    "The complicated school homework left the parents trying to help their kids quite confused.",
    "Peter found road kill an excellent way to save money on dinner.",
    "Honestly, I didn't care much for the first season, so I didn't bother with the second.",
    "As she walked along the street and looked in the gutter, she realized facemasks had become the new cigarette butts.",
    "I've never seen a more beautiful brandy glass filled with wine.",
    "The bees decided to have a mutiny against their queen.",
    "Edith could decide if she should paint her teeth or brush her nails.",
    "She insisted that cleaning out your closet was the key to good driving.",
    "Jenny made the announcement that her baby was an alien.",
    "Douglas figured the best way to succeed was to do the opposite of what he'd been doing all his life.",
    "Improve your goldfish's physical fitness by getting him a bicycle.",
    "100 years old is such a young age if you happen to be a bristlecone pine.",
    "The balloons floated away along with all my hopes and dreams.",
    "Her dad offered to visit her, but she turned him down.",
    "The ocean is my favorite view.",
    "She dreamed of one day having the flexibility to take a day off whenever she felt sick.",
    "He has quite a few friends.",
    "Being fashionable is not expensive.",
    "I only like certain brands of clothes.",
    "They speak English at work.",
    "He slowly began to realize the error of his ways.",
    "I will get sick from that.",
    "His parents went to Madrid for the week, so he threw a party and invited half the school."
];